/*
Problem 2
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int ft_even_fibonacci() {
    int prev = 1;
    int curr = 2;
    int next = prev + curr;
    int sum = curr;
    while (next < 4e6) {
        if(next % 2 == 0) {
            sum += next;
        }
        prev = curr;
        curr = next;
        next = prev + curr;
    }
    return sum;
}

int main() {
    printf("%d\n", ft_even_fibonacci());
    return 0;
}